### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by mgoodfellow** [justeat/kongverge#21]
We need to run integration tests against real Kong instances.

1. This could be done against a local docker container (dev experience)
2. This would be hard to do one the TC build agents currently, as we would need a custom image baked I believe that had all our build tools & docker on it. Furthermore, each build would probably pull down the Kong docker images.
3. We could run the CI build integration tests against QA

On this note, I just realised while writing plugins, that some will need to be run against Kong CE and some against Kong EE.

I think we should use NUnit categories to tag our tests (`CE` or `EE`)

eg. `[Category("CE")]`

Then the build job can run these against specific instances as required. The actual hostnames of the Kong instances should probably be injected via env variables using TC params.

**Comment by TomFreeman** [comment]
The docker version is being implemented now. Just need to get AppVeyor to play nicely.
