### ISSUE TITLE
Can not access host with basic auth

### ISSUE THREAD

**Issue by MrFix93** [justeat/kongverge#26]
We enabled basic auth on our Kong node. However, Kongverge does not support such a form of authentication, yet. In addition, the error code does not provide an appropiate error code. Am I doing something wrong, or isn't it supported, yet?

```
C:\Users\p.wessels>kongverge --host localhost --port 7001 --output C:\Users\p.wessels\Desktop --verbose
[16:50:25 INF] ************** Kongverge 1.2.0.150 **************
[16:50:25 INF] Exporting configuration from Kong
[16:50:25 ERR] Specified host unreachable
```

**Comment by shaynevanasperen** [comment]
@MrFix93 Support for Basic Authentication has now been released. See the release notes for details of breaking changes: https://github.com/justeat/kongverge/releases/tag/2.0.0
