### ISSUE TITLE
Routes should always start with "/"

### ISSUE THREAD

**Issue by TomFreeman** [justeat/kongverge#40]
Kongverge will allow regex patterns that don't match this requirement.

Kongverge could easily reject routes configured without a "/" as the initial character.

The [only documentation](https://docs.konghq.com/0.14.x/proxy/#configuring-a-fallback-route) around this doesn't appear to call this out as a specific requirement - however it does call out that the routes are anchored on matching the first character anyway, so it makes no sense for a route that doesn't start with a "/" character.

**Comment by shaynevanasperen** [comment]
I actually attempted to do this when I was adding the route validation logic to Kongverge recently, and then gave up when I realized that route paths can be regex patterns that start with something other than a `/`. For example, we can have a regex that starts with `(?i)` to signify case-insensitivity, or `^` to signify the beginning of the string to be matched.

**Comment by TomFreeman** [comment]
We have the same issue at the end as well, trailing slashes are invalid routes.

For our purposes we can validate configuration in CI by deploying to a dockerized kong image, but as the rules are theoretically simple it would be nice to validate this automatically.

But as you say, they're not actually as simple as they seem.

**Comment by shaynevanasperen** [comment]
It turns out that Kong rejects any route that doesn't start with a `/` anyway (even if it's just a regex case-insensitivity flag like `(?i)`). So I'll add this check to the built-in validation of Kongverge.
